// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRg9aLuzaSzCig8NXhW5I__6gHjsBa-QA',
    appId: '1:982807142432:web:5374e06ffd41850d59dc45',
    messagingSenderId: '982807142432',
    projectId: 'reso-29a8f',
    authDomain: 'reso-29a8f.firebaseapp.com',
    storageBucket: 'reso-29a8f.firebasestorage.app',
    measurementId: 'G-HRXC21YL6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnK5OYXil5irZXcwHbpq9UCQ5Vk_8mAZE',
    appId: '1:982807142432:android:15b7df9b811d3f3859dc45',
    messagingSenderId: '982807142432',
    projectId: 'reso-29a8f',
    storageBucket: 'reso-29a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJieFLkQItty-7oXYWNkUCfvIl8KU5Jak',
    appId: '1:982807142432:ios:dc56b5d8c276d8d959dc45',
    messagingSenderId: '982807142432',
    projectId: 'reso-29a8f',
    storageBucket: 'reso-29a8f.firebasestorage.app',
    iosBundleId: 'com.trapizino.reso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJieFLkQItty-7oXYWNkUCfvIl8KU5Jak',
    appId: '1:982807142432:ios:dc56b5d8c276d8d959dc45',
    messagingSenderId: '982807142432',
    projectId: 'reso-29a8f',
    storageBucket: 'reso-29a8f.firebasestorage.app',
    iosBundleId: 'com.trapizino.reso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRg9aLuzaSzCig8NXhW5I__6gHjsBa-QA',
    appId: '1:982807142432:web:94811116890c7c8259dc45',
    messagingSenderId: '982807142432',
    projectId: 'reso-29a8f',
    authDomain: 'reso-29a8f.firebaseapp.com',
    storageBucket: 'reso-29a8f.firebasestorage.app',
    measurementId: 'G-Z8RQ9KMZ55',
  );
}
